INFRA: Initialize Build Project
Mums-Who-Code/ArtGallery.Web pull request #2
Opened 2022-03-19 22:32 UTC by NaynaMallick

closes #1

2022-03-20 03:37 UTC, ShriHumrudha requested changes

2022-03-20 03:37 UTC, ShriHumrudha commented on .github/workflows/dotnet.yml
> +        dotnet-version: 6.0.100
Go with latest

2022-03-26 14:45 UTC, NaynaMallick commented on .github/workflows/dotnet.yml
> +        dotnet-version: 6.0.100
resolved

2022-03-26 14:54 UTC, ShriHumrudha approved these changes

2022-03-26 14:54 UTC, merged