INFRA: Initialize Web Project
Mums-Who-Code/ArtGallery.Web pull request #3
Opened 2022-04-02 21:43 UTC by NaynaMallick

2022-04-04 17:54 UTC, ShriHumrudha requested changes

2022-04-04 17:54 UTC, ShriHumrudha commented on ArtGallery.Web.Api/appsettings.Development.json
> +{
Ignore this file

2022-04-05 01:03 UTC, NaynaMallick commented on ArtGallery.Web.Api/appsettings.Development.json
> +{
removed

2022-04-05 02:22 UTC, ShriHumrudha approved these changes

2022-04-05 04:45 UTC, merged